### ISSUE TITLE
Splash screen message wrong approach?

### ISSUE THREAD

**Issue by immortius** [MovingBlocks/SplashScreen#1]
This is an issue I previously fixed (I think, unless that was on a branch), but has been reintroduced during the migration into a library.

The Splash screen maintains a queue of upcoming messages, and works through them one by one at a fixed time per message. However, this makes it vulnerable to flooding - if messages are received faster than the fixed time, the displayed message will lag further and further behind the current activity.

Instead I suggest the splash screen should only queue up a single message - if a new message is posted, that should override the currently queued message. This will result in some messages not being shown, but will mean that the splash screen's message will reflect the current or recent activity.

**Comment by msteiger** [comment]
That's correct - I will add a method to configure the behavior of the splash screen.
